name: Mineracao Automatica Amazon

on:
  schedule:
    - cron: '0 08 * * *' # Roda às 05:00 da manhã de Brasília
  workflow_dispatch: # Ativa o botão manual

jobs:
  mineracao:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Instalar tudo
        run: |
          pip install streamlit playwright pandas
          playwright install chromium
      - name: Rodar Robo
        run: python robo.py
      - name: Salvar no GitHub
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dados_fba.json
          git commit -m "Update automatico" || exit 0
          git push
