name: Mineracao Automatica Amazon

on:
  schedule:
    - cron: '0 08 * * *'
  workflow_dispatch: 

jobs:
  mineracao:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Instalar Dependencias
        run: |
          pip install playwright
          pip install -r requirements.txt
          playwright install chromium

      - name: Executar Robo
        run: python robo.py

      - name: Salvar no GitHub
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dados_fba.json
          git commit -m "Update automatico: $(date +'%Y-%m-%d %H:%M')" || exit 0
          git push
